# Site settings
title: Manim Devs
# email:
# description: "Job Board for Manim Developers | Hire Manim Developers to produce your math animations using Manim"
description: "Job Board for Manim Developers"
# url: "https://manimjobs.xyz"
# baseurl: ""
# twitter_username: ""

# Build settings
markdown: kramdown
permalink: pretty
theme: "minima"

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

header_pages:
  - devs.md
  - jobs.md
  - about.md

minima:
  skin: dark

# configure kramdown
kramdown:
  parse_block_html: true

highlighter: rouge

excerpt_separator: <!--more-->
