# Site settings
title: manim.dev
# email:
# description: "Job Board for Manim Developers | Hire Manim Developers to produce your math animations using Manim"
description: "A Roster and Job Board for Manim Developers"
# url: "https://manimjobs.xyz"
# baseurl: ""
# twitter_username: ""

# Build settings
markdown: kramdown
permalink: pretty
# theme: "minima"
remote_theme: jekyll/minima

collections:
  devs:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme

header_pages:
  - about.md

minima:
  skin: dark

# configure kramdown
kramdown:
  parse_block_html: true

highlighter: rouge

excerpt_separator: <!--more-->
